name: twist
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluro: ^1.6.3
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  cupertino_icons: ^0.1.3
  hive: ^1.2.0
  hive_flutter: ^0.3.0+1
  uuid: 2.2.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter
  lint: 1.2.0

dependency_overrides:
  analyzer: '0.39.14' # https://github.com/flutter/flutter/issues/62240

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Italic.ttf
          style: italic
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
  
  assets:
    - assets/placeholder.png