name: on_master

on:
  push:
    branches:
      - master
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: twist-android
          path: build/app/outputs/apk/release/
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
      - run: flutter channel beta
      - run: flutter upgrade
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - uses: actions/upload-artifact@v2
        with:
          name: twist-web
          path: build/web/
  build-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
      - run: flutter channel dev
      - run: flutter upgrade
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos
      - uses: actions/upload-artifact@v2
        with:
          name: twist-macOS
          path: build/macos/Build/Products/**/*.app
