name: on_master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: twist-android
          path: build/app/outputs/apk/release/
